### ISSUE TITLE
fourth movement, more score :)

### ISSUE THREAD

**Issue by matheusbonjour** [MennovDijk/bilge_bot#2]
how can i add a fourth movement without losing my memory in the 12x6 matrix? I tried to create a search for a fourth bilge board, requiring a higher score, but I couldn't...

**Comment by matheusbonjour** [comment]
oh, congrats on the bot... good programming skills.

**Comment by MennovDijk** [comment]
Thanks, appreciate the comment. It's not great, but I managed to do it without spending too much time on it. All you would need to do is indeed create the fourth bilge board. The issue is that the number of possible moves increases exponentially. Right now it does 120 checks per individual board. So the number of checks with only depth = 1 would be 60*120 = 7200. Number of checks at depth = 2 would be 60*7200 = 432000. Extrapolating that to depth=4 would be 1555200000 checks. That's a lot of memory taken up + a lot of compute. Not saying it's impossible, but doing depth=4 instead of depth=3 takes 60 times more memory and compute. There are some tricks to reduce that (multi-threading, numexpr), but haven't had the chance to work on that yet.
